### PR TITLE
Add request name and description to template.

### PR DESCRIPTION
**Pull request by Zodiase**

### CODE REVIEW

**Comment by JonathanMontane** [comment]
Hey @Zodiase,
thank you for your contribution. Unfortunately, we cannot accept the PR as it is, as multiline descriptions will break the comment section and spill over to the code section.

consider using this structure instead when there are multiple lines in the description:

``` sh
: '{{{request.description}}}'
```

This solution is only nice when there are multiple lines, and quite ugly for single line comments, though. Maybe check for the number of lines and pick the best format for it ?

**Comment by Zodiase** [comment]
I see. Probably why none of the exporters I've used so far actually cared to export the descriptions.

I don't like any of the shell comment block solutions. So I made a bit of change to add a cUrl exporter specific request property `cURLDescription` that guarantees to have a `#` before every line of the description.

**Comment by JonathanMontane** [comment]
Awesome!
A minor suggestion would be to drop the `#` in front of `{{{request.cURLDescription}}}` in `curl:mustache`, then you wouldn't have to care about index in `cURLCodeGenerator.coffee`.

I'll leave you some time to fix it if you want to, but if you don't want/care, I'll merge it as soon as you get back to me.

Thank you for your contribution :+1:

**Comment by Zodiase** [comment]
The reason for leaving out the first `#` from the logic is to make the mustache template make more sense semantically on its own. I'd rather leave it like this.

**Comment by JonathanMontane** [comment]
Alright!
Thanks for the contribution

**Pull request merged**
